import { NextRequest, NextResponse } from 'next/server'
import { execFile } from 'child_process'
import path from 'path'
import { requireAuth } from '@/lib/requireAuth'

// Safe person_id pattern: alphanumeric + underscore + hyphen only, 1-80 chars.
// Matches IDs generated by pipeline.py (e.g. "jagan_abc123", "stranger_visitor_7f3b").
const PERSON_ID_RE = /^[a-zA-Z0-9_-]{1,80}$/

export async function DELETE(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const denied = requireAuth(req); if (denied) return denied
  const { id } = params
  if (!id || !PERSON_ID_RE.test(id)) {
    return NextResponse.json(
      { error: 'Invalid ID — must be alphanumeric/underscore/hyphen, 1–80 chars' },
      { status: 400 }
    )
  }

  const scriptPath = path.join(process.cwd(), '..', 'delete_person.py')
  const pythonPath = process.env.PYTHON_PATH || 'python'

  return new Promise((resolve) => {
    // execFile does NOT invoke a shell — each argument is a separate argv element,
    // so the id value cannot inject shell commands regardless of its content.
    execFile(
      pythonPath,
      [scriptPath, '--id', id],
      { cwd: path.join(process.cwd(), '..') },
      (error, _stdout, stderr) => {
        if (error) {
          console.error('[Delete] Failed:', stderr || error.message)
          resolve(NextResponse.json({ error: 'Delete failed' }, { status: 500 }))
        } else {
          resolve(NextResponse.json({ success: true }))
        }
      }
    )
  })
}
